version: '3'

services:

  ursa-major-db:
    image: postgres:14.4
    volumes:
      - ursamajordb:/var/lib/postgresql/data/

  ursa-major-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8005}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8005}:${APPLICATION_PORT:-8005}"
    depends_on:
      - ursa-major-db

volumes:
  ursamajordb:
