# Generated by Django 2.0.8 on 2018-11-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='archivesspace_identifier',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='archivesspace_identifier',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='archivesspace_parent_identifier',
        ),
    ]
