# Generated by Django 2.2.8 on 2020-01-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0002_auto_20181119_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='accession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bagdiscovery.Accession'),
        ),
    ]
