# Generated by Django 2.2.8 on 2020-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0003_auto_20200127_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='origin',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('legacy_digital', 'Legacy Digital Processing'), ('digitization', 'Digitization')], default='aurora', max_length=20),
        ),
    ]
