# Generated by Django 2.2.8 on 2020-02-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0004_bag_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='process_status',
            field=models.CharField(choices=[(1, 'Created'), (2, 'Discovered'), (3, 'Delivered')], default=1, max_length=20),
        ),
    ]
