# Generated by Django 2.2.10 on 2020-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0005_bag_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='type',
            field=models.CharField(blank=True, choices=[('aip', 'Archival Information Package'), ('dip', 'Dissemination Information Package')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='process_status',
            field=models.IntegerField(),
        ),
    ]
