# Generated by Django 3.2.5 on 2021-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0006_auto_20200317_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
