# Generated by Django 4.0.2 on 2022-02-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagdiscovery', '0008_alter_bag_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='process_status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Discovered'), (3, 'Delivered'), (4, 'Discovering'), (5, 'Delivering')], default=1),
        ),
    ]
